config/routes.rb
StartwalkApp::Application.routes.draw do
  
  
  match 'contact' => 'staticpages#contact', :as => :contact
  match 'service' => 'staticpages#service', :as => :service
  match 'privacy' => 'staticpages#privacy', :as => :privacy
  match 'whybuy' => 'staticpages#whybuy', :as => :whybuy
  match 'launch' => 'staticpages#launch', :as => :launch
  match 'about' => 'staticpages#about', :as => :about
  match 'howlaunch' => 'staticpages#howlaunch', :as => :howlaunch
  match 'howbuy' => 'staticpages#howbuy', :as => :howbuy
  



  devise_for :partners, :controllers => {
        :registrations => "registrations",
        :omniauth_callbacks => "users/omniauth_callbacks"
      } do
        get "logout" => "devise/sessions#destroy"
      end
  
  match 'pages/login'
  
  match 'projects/:id/support' => 'Projects#support', :as => :project_support
  
  
end

app/views/shared/_content_page.html.erb
<%
  # provide a default array for collecting CSS for sections
  css = []

  # if 'sections' is passed in as a local_assigns, all of this is ignored.
  if local_assigns[:sections].blank?
    # always have a title
    sections = [{:yield => :body_content_title, :fallback => page_title, :title => true}]

    # append sections from this page.
    @page.parts.inject(sections) do |s, part|
      # we have some default yields, body_content_left and body_content_right
      # these map to 'body' and 'side_body' fields in default Refinery.
      section = {:fallback => part.body}
      section[:yield] = case (title_symbol = part.title.to_s.gsub(/\ /, '').underscore.to_sym)
        when :body then :body_content_left
        when :side_body then :body_content_right
        else title_symbol
        end

      # add section to the list unless we were specifically requested not to.
      # otherwise, add css saying it's been removed.
      unless (local_assigns[:hide_sections]||=[]).include?(section[:yield])
        s << section
      else
        css << "no_#{section[:yield]}"
      end
    end unless @page.nil? or @page.parts.blank?

    # Ensure that even without @page.parts we still have body_content_left and body_content_right
    all_yields = sections.collect{|s| s[:yield]}
    sections << {:yield => :body_content_left} unless all_yields.include?(:body_content_left)
    sections << {:yield => :body_content_right} unless all_yields.include?(:body_content_right)
  end

  # you can add more sections to the list using something like this:
  # sections |= [{:yield => :something_else, :fallback => another_method, :id => 'something'}]

  sections.each do |section|
    section[:html] = yield(section[:yield]) if section[:yield].present?

    if section[:html].blank? and !local_assigns[:show_empty_sections] and
       !local_assigns[:remove_automatic_sections] and section.keys.include?(:fallback) and
       section[:fallback].present?
      section[:html] = raw(section[:fallback])
    end

    dom_id = section[:id] || section[:yield]
    if section[:html].present?
      if section[:title]
        section[:html] = "<h1 id='#{dom_id}'>#{section[:html]}</h1>".html_safe
      else
        section[:html] = "<section id='#{dom_id}'><div class='inner'>#{section[:html]}</div></section>".html_safe
      end
    else
      css << "no_#{dom_id}"
    end
  end
-%>
<section id='body_content'<%= " class='#{css.join(' ')}'" if css.present? %>>
  <% raw sections.map{|section| section[:html]}.join("\n") -%>
</section>

<%= render :partial => '/shared/draft_page_message' unless @page.nil? or @page.live? -%>

app/views/shared/_draft_page_message.html.erb
<aside class='page_not_live'>
  <%= t('.not_live') %>
</aside>

app/views/shared/_footer.html.erb
<!-- <p>
  <%= t('.copyright', :year => Time.now.year,
                      :site_name => RefinerySetting.find_or_set(:site_name, "Company Name")) %>
</p> -->

<div class="bottomFrmae">
  <ul class="menuFrame">
      <li><%= link_to "關於我們", about_path %></li>
      <li class="menuline">│</li>
      <li><%= link_to "如何發起專案", howlaunch_path %></li>
      <li class="menuline">│</li>
	  <li><%= link_to "如何預購", howbuy_path %></li>
      <li class="menuline">│</li>
      <li><%= link_to "聯絡我們", contact_path %></li>
      <li class="menuline">│</li>
      <li><%= link_to "服務條款", service_path %></li>
      <li class="menuline">│</li>
      <li><%= link_to "隱私權政策", privacy_path %></li>
  </ul>
	<div class="logo"></div>
</div>

app/views/shared/_google_analytics.html.erb
<% unless refinery_user? or
  (page_code = RefinerySetting.find_or_set(:analytics_page_code, 'UA-xxxxxx-x').to_s.strip) =~ /^(UA-xxxxxx-x)?$/ -%>
<!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet -->
<script>var _gaq=[['_setAccount','<%= page_code %>'],['_trackPageview'],['_trackPageLoadTime']];(function(d,t){
var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.async=1;g.src='//www.google-analytics.com/ga.js';s.parentNode.insertBefore(g,s)
}(document,'script'))</script>
<% end -%>

app/views/shared/_head.html.erb
<head>
  <meta charset='<%= ::Refinery::Application.config.encoding %>' />
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /><![endif]-->
  <!-- <title><%= browser_title(yield(:title)) %></title> -->
  <%= raw "<meta name=\"description\" content=\"#{@meta.meta_description}\" />" if @meta.meta_description.present? -%>
  <%= raw "<meta name=\"keywords\" content=\"#{@meta.meta_keywords}\">" if @meta.meta_keywords.present? -%>
  <%= csrf_meta_tag if RefinerySetting.find_or_set(:authenticity_token_on_frontend, true)-%>
  <%= yield :meta %>

  <%= stylesheet_link_tag stylesheets_for_head(stylesheets||=%w(application formatting theme), theme ||= nil),
                          :cache => ("cache/application" if Rails.root.writable? and
                                                            RefinerySetting.find_or_set(:use_resource_caching, true) and
                                                            request.env['HTTP_USER_AGENT'] !~ /MSIE/ and (theme ||= nil).blank?) %>
  <%= stylesheet_link_tag "home", :theme => theme if home_page? %>

  <%= yield :stylesheets %>
  <%= render :partial => '/shared/google_analytics' unless local_request? %>

  <%= javascript_include_tag 'modernizr-min' %>
  <%= javascript_include_tag 'jquery-1.7.1.min.js' %>
  <%= javascript_include_tag 'jquery.nivo.slider.js' %>
  <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
  </script>

  <title>傑克魔豆</title>

</head>

app/views/shared/_header.html.erb
<!-- <% if @current_patner.nil? %>
<%= link_to 'Login', pages_login_path %>
<% else %>
<%= link_to 'Logout', logout_path %>
<% end %> -->

<!-- <%= link_to '註冊'%>
<%= link_to '登入'%>

<%= link_to '夢想'%>
<%= link_to '公益'%>
<%= link_to '文創'%>
<%= link_to '科技'%>
<%= link_to '活動'%>
<%= link_to '遊戲'%>
<%= link_to '推薦'%>
<%= link_to '已結束'%>

-->

<%= render(:partial => "/shared/menu", :locals => {
             :dom_id => 'menu',
             :css => 'menu'
           }) %> 

<div id="framecontent">
	<div class="innertube">
		<div class="titleFrame">
			<table width="900" border="0" cellspacing="0" cellpadding="0">
  				<tr>
					<a href="/home">
    				<div class="logo_form"><td></td></div>
					</a>
    				<td>
						<div class="title_1bn">
							<%= link_to "發起專案", launch_path %>
						</div>
						<div class="title_2bn">
							<%= link_to "為何要預購", whybuy_path %>
						</div>
						<!-- 
						<div class="facebooklogo">
							<a href="#">登入</a>
						</div>
						 -->
					</td>
  				</tr>
			</table>
		</div>
	</div>
</div>

app/views/shared/_html_tag.html.erb
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html lang="<%= ::I18n.locale %>" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<%= ::I18n.locale %>" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<%= ::I18n.locale %>" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<%= ::I18n.locale %>" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]> <html lang="<%= ::I18n.locale %>" class="no-js"> <![endif]-->

app/views/shared/_ie6check.html.erb
<% if RefinerySetting.find_or_set(:ie6_upgrade_message_enabled, true) -%>
  <% unless admin? %>
  <!--[if lte IE 6]>
    <div id="ie6msg_wrapper">
      <div id="ie6msg">
        <h4>Did you know that your browser is out of date?</h4>
        <div id='ie6message'>
          <p>
            To get the best possible experience using our website we recommend that you upgrade your browser to a newer version. The current version is
            <a class="getie8" href="http://upgradeie.s3.amazonaws.com/eng/index.html">Internet Explorer 8</a>.
            The upgrade is free. If you're using a PC at work you should contact your IT administrator.
          </p>
          <p>
            If you want to you may also try some other popular and <strong>free</strong> Internet browsers like:<br/>
            <a class="ie6expl" href="http://www.google.com/chrome" target='_blank'>Google Chrome</a>,
            <a class="ie6expl" href="http://www.apple.com/safari/download/" target='_blank'>Safari</a>,
            <a class="ie6expl" href="http://getfirefox.com" target='_blank'>Firefox</a> or
            <a class="ie6expl" href="http://www.opera.com" target='_blank'>Opera</a>
          </p>
        </div>
      </div>
    </div>
  <![endif]-->
  <% else %>
    <!--[if lte IE 8]>
      <div id='upgrade_wrapper'>
        <h2>Want to have a better experience with Refinery?</h2>
        <p>
          To get the best possible experience using Refinery, we recommend that you switch your web browser.
        </p>
        <p>
          There are a number of web browsers available that will give you a better experience and they are all available <strong>free of charge</strong>. Installing a new web browser will not remove Internet Explorer which you will still be able to use when you need to.
        </p>
        <p>
          <ul>
            <li>
              <a class="ie6expl" href="http://www.google.com/chrome" target='_blank'>Google Chrome</a>
            </li>
            <li>
              <a class="ie6expl" href="http://www.apple.com/safari/download/" target='_blank'>Apple Safari</a>
            </li>
            <li>
              <a class="ie6expl" href="http://getfirefox.com" target='_blank'>Mozilla Firefox</a>
            </li>
            <li>
              <a class="ie6expl" href="http://www.opera.com" target='_blank'>Opera</a>
            </li>
          </ul>
        </p>
      </div>
    <![endif]-->
    <% content_for :javascripts do %>
      <script>
        $(document).ready(function() {
          $('#flash.flash_message:has("#upgrade_wrapper") #flash_close').click(function(e) {
            e.preventDefault();
            $.get('<%= admin_disable_upgrade_message_path %>');
          });
        });
      </script>
    <% end %>
  <% end %>
<% end -%>

app/views/shared/_javascripts.html.erb
<%= yield :before_javascript_libraries -%>
<%= yield :javascript_libraries %>
<%= yield :after_javascript_libraries %>
<% if request.env['HTTP_USER_AGENT'] =~ /MSIE/ %>
  <!--[if lt IE 7 ]>
    <%= javascript_include_tag 'dd_belatedpng' %>
    <script> DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images </script>
  <![endif]-->
<% end %>
<%= yield :javascripts -%>

app/views/shared/_menu.html.erb
 <%
  # Collect the root items.
  # Refinery::Menu is smart enough to remember all of the items in the original collection.
  if (roots = local_assigns[:roots] || (collection ||= @menu_pages).roots).present?
    dom_id ||= 'menu'
    css = [(css || 'menu'), 'clearfix'].flatten.join(' ')
    hide_children = RefinerySetting.find_or_set(:menu_hide_children, false) if hide_children.nil?
-%>
<nav id='<%= dom_id %>' class='<%= css %>'>
  <ul>
    <%= render :partial => '/shared/menu_branch', :collection => roots,
               :locals => {
                 :hide_children => hide_children,
                 :sibling_count => (roots.length - 1),
                 :apply_css => true #if you don't care about class='first' class='last' or class='selected' set apply_css to false for speed.
               } -%>
  </ul>
</nav>
<% end -%> 

app/views/shared/_menu_branch.html.erb
<!-- <%
  if !!local_assigns[:apply_css] and (classes = menu_branch_css(local_assigns)).any?
    css = "class='#{classes.join(' ')}'".html_safe
  end
  # dom_id DEPRECATED: REMOVE AT 1.1, serves no purpose same with css attributes 'first' and 'last'
  dom_id = "id='item_#{menu_branch_counter}'".html_safe if menu_branch.parent_id.nil?
-%>
<li<%= ['', css, dom_id].compact.join(' ').gsub(/\ *$/, '').html_safe %>>
  <%= link_to menu_branch.title, menu_branch.url -%>
  <% if (children = menu_branch.children unless hide_children).present? -%>
    <ul class='clearfix'>
      <%= render :partial => '/shared/menu_branch', :collection => children,
                 :locals => {
                   :apply_css => local_assigns[:apply_css],
                   :hide_children => !!hide_children
                 } -%>
    </ul>
  <% end -%>
</li> -->

app/views/shared/_message.html.erb
<% flash.each do |key, value| %>
<div id='flash' class="flash flash_<%= key %>" style='visibility: hidden;' >
  <%= value %>
  <% if key.to_s == "message" %>
    <%= link_to t('.close_this_message'), "", {:id => "flash_close"} %>
  <% else %>
    <%= link_to t('.close'), "", {:id => "flash_close"} %>
  <% end %>
</div>
<% end %>

app/views/shared/_no_script.html.erb
<noscript>
  <div class='flash flash_error'>
    <%= t('.enable_javascript_html') %>
    <%= t('.here_are') %>
    <%= link_to t('.instructions_enable_javascript_html'),
                'http://www.enable-javascript.com',
                :target => '_blank' %>
  </div>
</noscript>

app/views/shared/_site_bar.html.erb
<% if refinery_user? %>
  <% unless admin? # all required JS included by backend. %>
    <% content_for :stylesheets, stylesheet_link_tag('refinery/site_bar') unless !!local_assigns[:exclude_css] %>
    <%= yield(:stylesheets) unless local_assigns[:head] or local_assigns[:exclude_css] %>
  <% end -%>
  <div id='site_bar'>
    <div id='site_bar_content' class='clearfix'>
      <div id='editor_switch'>
        <%= site_bar_switch_link -%>
      </div>
      <%= link_to image_tag("#{"http://refinerycms.com/images/" unless local_request?}refinery/logo-site-bar.png", :alt => "Refinery (tm) Content Manager"),
                  'http://refinerycms.com',
                  :target => '_blank',
                  :id => 'site_bar_refinery_cms_logo' %>

      <div id='site_bar_branding'>
        <span id='site_bar_company_name'>
          <%= RefinerySetting.find_or_set(:site_name, 'Company Name') %>
        </span>

        <%= link_to t('.log_out', site_bar_translate_locale_args),
                    destroy_user_session_path, :id => 'logout' %>
      </div>
    </div>
  </div>
<% end %>